// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify.

const awsmobile = {
  aws_project_region: 'us-west-2',
  aws_appsync_graphqlEndpoint: 'https://m6357ab44jc2fcoaqehkfojws4.appsync-api.us-west-2.amazonaws.com/graphql',
  aws_appsync_region: 'us-west-2',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-mpypiojsezdylimjssv7vsbbqy',
};

export default awsmobile;
